#!/bin/sh
# shellcheck disable=SC2086,SC3045

main () {
  expected=false
  file='/etc/profile'
  init_file="--init-file ${file}"
  login="-l"
  rcfile="--rcfile ${file}"
  skip=false
  for arg do
    case "${arg}" in
      --init-file|--noprofile) $skip || unset init_file ;;
      -l|--login) $skip || unset login ;;
      --rcfile|--norc) $skip || unset rcfile ;;
      -O|+O|-o|+o) expected=true ;;
      --|-c|-s) skip=true ;;
      -*|+*) true ;;
      *) ! $expected || { skip=true; expected=false; } ;;
    esac
  done

  name="$(basename "${0}")"
  path="$(cd "$(dirname "${0}")" || exit 1; pwd)/${name}"
  scripts="$(type -aP "${name}" || which -a "${name}")" || { echo "${name}: ${name}: command not found"; exit 1; }

  for i in ${scripts}; do
    cmd="$(cd "$(dirname "${i}")" || exit 1; pwd)/${name}"
    if [ "${cmd}" = "${path}" ] || head -1 "${cmd}" | grep -q '^#\!'; then continue; else break; fi
  done
  [ ! "${cmd}" ] || { echo "${name}: ${cmd}: command not found"; exit 1; }

  echo "exec ${cmd} ${init_file} ${rcfile} ${login} ${*:-}" >/tmp/"${USER}-${name}"

  if [ "${1-}" ]; then
    exec ${cmd} ${init_file} ${rcfile} ${login} "${@}"
  else
    exec ${cmd} ${init_file} ${rcfile} ${login}
  fi
}

if [ "${1-}" ]; then main "${@}"; else main; fi
