#!/bin/sh

main () {
  name="$(basename "${0}")"
  cmd="$(has -v "${name}")"
  echo "exec ${cmd} ${*}" 2>/tmp/"${name}"
  if [ "${cmd-}" ]; then
    exec ${cmd:+${cmd} -i} "${@}"
  else
    "${@}"
  fi
}

main "${@}"


