// suppress inspection "AsciiDocAttributeShouldBeDefined" for whole file
= doctitle(1)
:doctype: manpage
:man-linkstyle: pass:[blue R < >]
:page-layout: base

== NAME

{name} - converts, tests and commit changes for AsciiDoc man pages in a repository

== SYNOPSIS

*{name}* [_OPTION_] [_DIRECTORY_]

== DESCRIPTION

The *{name}* command will use as sources: _src/man/*.adoc_ and _README.adoc_, relative to _DIRECTORY_. +

Generated man pages will be copied, if changed to _share/man/man[1-8]_. +

Name and section for *README* will be obtained from: _= doctitle(1)_.

== OPTIONS

*DIRECTORY*::
  _DIRECTORY_ in a git repository (default: git top of current working directory).

*-h, --help*::
  Show man page and exit.

== Exit status

*0*::
  Success.

*1*::
  Invalid git repository. +
  Error converting from AsciiDoc to man page. +
  Testing error.

== EXAMPLES

_$_ *{name}*

_$_ *{name}* src/man

== REPOSITORY

{repo}

== RESOURCES

*GitHub:* https://github.com/{owner}/{repo}

== COPYING

Copyright (C) 2021-present {author}. +
Free use of this software is granted under the terms of the MIT License.

== SEE ALSO

asciidoctor(1)
